### ISSUE TITLE
I get many warnings that look like this on the console. What does this mean?  Can I stop the warnings?

### ISSUE THREAD

**Issue by coderextreme** [create3000/cobweb#12]
[.CommandBufferContext.Offscreen-MainThread-0000020A509DC880]RENDER WARNING: there is no texture bound to the unit 0
cobwebframe.html:1 [.CommandBufferContext.Offscreen-MainThread-0000020A509DC880]RENDER WARNING: there is no texture bound to the unit 1

**Comment by create3000** [comment]
Should be fixed a resent version.
