### ISSUE TITLE
Using xhtml causes not well formed exception

### ISSUE THREAD

**Issue by andreasplesch** [create3000/cobweb#13]
Here is the same page using html and xhtml:

http://andreasplesch.github.io/Library/Uses_html.html
http://andreasplesch.github.io/Library/Uses_xhtml.xhtml

The xhtml page fails and there is a not well formed exception in the console.

I think I tracked the exception down to

https://github.com/create3000/cobweb/blob/master/cobweb.js/cobweb/Browser/Core/BrowserTimings.js

where html table construction seems to miss closing tags in various places.

See

http://stackoverflow.com/questions/6555898/jquery-when-creating-a-new-element-do-i-need-the-ending-tag

But I did not try to fix it there, so I am not sure if this is the issue.

**Comment by andreasplesch** [comment]
in xhtml attributes need to be quoted, so colspan='2'

**Comment by andreasplesch** [comment]
It looks like jquery generated context menu also does not work for xhtml. I left an issue there:

https://github.com/swisnl/jQuery-contextMenu/issues/450

**Comment by andreasplesch** [comment]
#14 should address BrowserTimings. It would be possible to patch contextMenu similarly hopefully by swisnl.

**Comment by create3000** [comment]
Added you to the list of authors.

**Comment by andreasplesch** [comment]
Thanks !
