### ISSUE TITLE
Chrome not working in 1.28

### ISSUE THREAD

**Issue by andreasplesch** [create3000/cobweb#16]
For me Chrome stopped working with 1.28 . Firefox is ok. 
Chrome has this error:
WebGL: INVALID_OPERATION: useProgram: program not valid

**Comment by create3000** [comment]
Have released a fix.

**Comment by andreasplesch** [comment]
Using the latest here https://rawgit.com/create3000/cobweb/69cc37503d1cea4d835a8a384ef923b169cdd963/stable/1/1.28/cobweb.js
on
https://andreasplesch.github.io/cobweb_dom/index.xhtml
I still get the WebGL error and before that
`Couldn't initialize ComposedShader 'GouraudShader'.`
on Chrome on Intel intergrated HD Graphics.
Firefox still works fine.

**Comment by andreasplesch** [comment]
I set a breakpoint where the error occurs at line 27728 in cobweb.js:

				gl .useProgram (this .program);

Just before the error occurs the WebGLProgram object this.program is there but the toString() does not report anything useful.

**Comment by andreasplesch** [comment]
It works now on Chrome on another laptop. I am closing this.

**Comment by andreasplesch** [comment]
I double checked. The same Chrome version on one laptop works, on the other does not. Both windows7, but one 32bit, one 64bit (not working). One Intel HD3000 gfx , the other Intel HD gfx but newer (I think 4000, not working). Really strange.
