### ISSUE TITLE
Some conformance Nist scenes for bindable nodes fail

### ISSUE THREAD

**Issue by andreasplesch** [create3000/cobweb#26]
for example:
http://www.web3d.org/x3d/content/examples/ConformanceNist/BindableNodes/NavigationInfo/headlight_rangeIndex.html
http://www.web3d.org/x3d/content/examples/ConformanceNist/BindableNodes/NavigationInfo/headlight_rangeCobweb.html

**Comment by create3000** [comment]
In file
http://www.web3d.org/x3d/content/examples/ConformanceNist/BindableNodes/NavigationInfo/headlight_rangeIndex.html
on load the NavigationInfo named »NAV1« is bound, if the box is clicked the TouchSensor sends and event to Script »LIGHTSWITCH« where from the other NavigationInfo named »NAV2« the _headlight_ field is toggled. That means all the time NAV1 is is bound, if the headlight field from NAV2 is toggled it MUST nothing happen.

I think the example is wrong and the NavigationInfo »NAV1« should be cloned to the place where »NAV2« is.

**Comment by andreasplesch** [comment]
In other words, NAV2 is never bound  and so changes to it do not affect the scene. Looking at the x3d, I agree and will ask on the list for feedback since this is an conformance example.

**Comment by andreasplesch** [comment]
Example is confirmed broken per feedback on list. Closing.
