### ISSUE TITLE
rendering artifacts for skinny triangles

### ISSUE THREAD

**Issue by andreasplesch** [create3000/cobweb#3]
An animated scene with skinny triangles from tessellation produces noticable rendering artifacts for both Gouraud and Phong shading:

http://andreasplesch.github.io/Library/Viewer/gears42P.html

I could not reproduce this with other scenes.

**Comment by create3000** [comment]
Fix commited.
!!! But please set for all Extrusions the convex field to false.

You can test it using the trunk version of cobweb.js:
https://rawgit.com/create3000/cobweb/master/cobweb.js/cobweb.min.js

**Comment by andreasplesch** [comment]
Thanks ! That worked great. Please feel free to use the gears example scene as one of your tests.
