### ISSUE TITLE
VRMLScript globals missing SFString

### ISSUE THREAD

**Issue by Sgeo** [create3000/cobweb#34]
VRMLScript scripts are unable to create SFStrings, it is missing from the relevant file: https://github.com/create3000/cobweb/blob/master/cobweb.js/cobweb/Components/Scripting/Script.js

**Comment by Sgeo** [comment]
Looking closer at the spec, it seems the Javascript API doesn't provide it? What gives? Is that intentional?

**Comment by create3000** [comment]
Yes it is intentional. X3D Scripts neither provide SFString, nor SFBool, SFInt32, SFFloat, SFDouble, SFTime. These types are converted to their JavaScript representation, ie. Number, String, Boolean.

**Comment by Sgeo** [comment]
Thank you. I'm trying to convert some old Cybertown assets into something more amenable to non-Blaxxun viewers like Cobweb, and I'm not very familiar with VRML (although I'm learning), so this was one of the things that came up.

On a related note, the VRML spec, if I'm understanding it correctly, suggests that diffuseColor does not apply for objects that have color textures on them, but Cobweb seems to be applying it anyway. Is this a Cobweb fault, or is X3D different? (A lot of other tools do this too). At least one Cybertown world had a bunch of nonsense diffuseColors that in Blaxxun viewer were hidden, but get used in other viewers.

**Comment by andreasplesch** [comment]
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/lighting.html#t-Litcolourandalpha

should be the relevant spec. table.

To me. it says that if you have a RGB texture, only the texture color is used. The Material diffuseColor is used with a one or two color texture which modulates intensity and/or alpha.
