### ISSUE TITLE
uniformMatrix4iv typo

### ISSUE THREAD

**Issue by Sgeo** [create3000/cobweb#37]
https://github.com/create3000/cobweb/blob/b88da29ce3f91e29cd79e071f78970414ee91285/cobweb.js/cobweb/Rendering/X3DRenderObject.js#L732

The line
```
gl .uniformMatrix4iv (shaderNode .x3d_Viewport, viewportArray);
```
says `uniformMatrix4iv`, which I assume should be `uniformMatrix4fv`. Also, I think it's supposed to have 3 arguments?

**Comment by create3000** [comment]
Thank you very much.
