### ISSUE TITLE
rotateYUp

### ISSUE THREAD

**Issue by andreasplesch** [create3000/cobweb#8]
GeoOrigin has a rotateYUp field. Issue is just for tracking.

**Comment by create3000** [comment]
I see that the specification is quite clear about the y-axis: _The rotateYUp field is used to specify whether coordinates of nodes that use this GeoOrigin are to be rotated such that their up direction is aligned with the X3D Y axis._ Does that mean the x-axis is also align with the X3D x-axis?

**Comment by andreasplesch** [comment]
I implemented rotateYUp in x3dom such that -Z aligns with the north direction. This is what would be expected and it makes the rotateYUp rotation the inverse of the GeoLocation rotation.

**Comment by create3000** [comment]
Fix commited.

**Comment by andreasplesch** [comment]
Great !
