### ISSUE TITLE
GeoTransform

### ISSUE THREAD

**Issue by andreasplesch** [create3000/cobweb#9]
I did not test GeoTransform but it does not look quite right. Here is a description:
https://sites.google.com/site/x3dgeo/x3d-geospatial-nodes/geotransform
I see if I can come up with a simple test scene.

**Comment by andreasplesch** [comment]
Here is the x3dom implementation

https://github.com/x3dom/x3dom/blob/master/src/nodes/Geospatial/GeoTransform.js#L124

**Comment by create3000** [comment]
Is there a practical example use case of GeoTransform with all values set available?

**Comment by andreasplesch** [comment]
There are a couple of examples here which exercise all fields:

http://andreasplesch.github.io/x3dom/

They should be pretty close standard x3d.

**Comment by andreasplesch** [comment]
These use GeoViewpoint. You can press 'v' to get a regular viewpoint printed out on the x3dom console.

**Comment by andreasplesch** [comment]
x3dom also has a non-standard globalGeoOrigin field:

http://doc.x3dom.org/author/Geospatial/GeoTransform.html

It provides a way to avoid having to repeatedly provide the same GeoOrigin field for all GeoNodes.

**Comment by create3000** [comment]
»x3dom also has a non-standard globalGeoOrigin field:«

this some kind of magic

**Comment by create3000** [comment]
Cobweb only implements standard Nodes and fields as there is enough to do with it.
GeoTransform: Fix commited.

**Comment by andreasplesch** [comment]
Understood.
